name: somemark
description: A very limited markdown parser
# version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  markdown: ^2.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
